export const pageCopy: Record<string, string> = {
  "archive-x": "ARCHIVE X\n\nArchive X investigates how images survive destruction and how memory reorganises itself through what remains. The project began with family photographs discovered in debris after my home was lost in South Lebanon.\n\nWorking across photography, video, sound, and installation, Archive X explores the moment between finding and understanding, between image and un-image—the transformation that occurs through damage and rupture.\n\nKonvent Zero Residency (2025): A two-week research period in Cal Rosal, Spain focused on material experimentation including emulsion transfer processes and spatial installation techniques.",
  "a-la-recherche-de-beyrouth":
    "À la recherche de Beyrouth Photography Series | Commissioned by Galerie Claude Lemand | Exhibited at Institut du Monde Arabe, Paris (2021) À la recherche de Beyrouth is a photographic series commissioned by Galerie Claude Lemand (Paris) and exhibited as part of the group show Lumières du Liban at the Institut du Monde Arabe (IMA) in 2021. The exhibition brought together contemporary Lebanese artis",
  "alternative-beirut":
    "Alternative Beirut stands as a creative agency that places itself at the cross-roads of culture, education, and social change. ALTERNATIVE BEIRUT",
  "artevolution":
    "ART EVOLUTION CINEMATOGRPAHY - MONTAGE ArtEvolution is a project of the Goethe-Institut, it is a support programme and production grant for emerging practitioners in the field of performing arts.with local partner organizations. Client Goethe Institute Year 2022 VIDEO SERIES In this documentary-style video series, we closely follow artists throughout their creative journey in crafting theatrical p",
  bokja:
    "BOKJA DESIGN The video series created for BOKJA's collection encapsulates the essence of their assemblage aesthetic. Through skilled cinematography and meticulous video editing, these pieces come to life, allowing viewers to immerse themselves in BOKJA's unique narrative. Nader Bahsoun / DIRECTOR; CINEMATOGRAPHER Aya Atwi / CO-DIRECTOR Mezyed / LIGHTING BOKJA",
  "commercial-content":
    "WOMENA - Sounds of Saudi PRE-INTEGRATION (Goethe) - Video Production BOKJA DESIGN - Fashion video series DAFTAR BEIRUT - Short video series ARTEVOLUTION - Short video series FRENCH EMBASSY - Trailer ZOUKAK - Short video series ALTERNATIVE BEIRUT - Content creation Jess & Alex - Wedding Film Noctiluca - Video Trailer & Photography",
  "daftar-beirut":
    "Daftar Beirut : Elie Boudjok | Episode 03 Meet Elie Boujok, the artisan behind \"Terre de Brume\" a craftsman who masterfully merges his background in special effects, cinema , and history to create elite kitchen knives designed for professionals. He is a true craftsman, focusing on tools that offer both form and function. Each handcrafted knife bears the unique mark of its maker—the perfect imperfe",
  fata17:
    "fata17 Sandy chamoun is beirut-based singer and musician better known as one of the founding member of the lebanese group “the great departed”. She is now a member of SANAM, a lebanese group from Lebanon . She released her first solo ep in December 2022 “fata17” . The album is conceptualized around field recording and sounds from the October 17 revolution in Lebanon. ALBUM COVER PHOTOSHOOT",
  "french-embassy":
    "Industrial Risk Management project FRENCH EMBASSY - 2022 A short documentary-style video produced for the French Embassy, capturing a cooperative training session between the French mission and the Lebanese army. The project focused on industrial risk management and civil safety procedures, highlighting the exchange of expertise and support in strengthening Lebanon’s emergency response capacities.",
  "fuel-project": "",
  "i-was-naver":
    "I Was Naver – Experimental Film\nScreened at Museum Night, Kunsthal Ghent (Belgium), December 2024\n\nI Was Naver is an experimental short film that reflects on the layered political and emotional terrain of Lebanon through a personal lens. The film traces the arc between two pivotal moments: the liberation of South Lebanon in 2000, seen through the eyes of my mother, and the 2019 uprising, which I documented firsthand with my camera. Between these events lies a landscape of permanent failures—yet within them, elusive victories continue to surface.\n\nThe work interrogates how we perceive and process these shifting realities, especially when mediated through images that are themselves distorted, manipulated, or incomplete. It invites viewers into a fragmented visual narrative where memory, personal history, and national trauma collide.\n\nThe film was screened at Museum Night at Kunsthal Ghent as part of a program curated by Firas El Hallak in collaboration with United Screens for Palestine. Shown alongside the work of other artists and filmmakers challenging dominant narratives, I Was Naver contributed to an evening of intimate, political, and transformative encounters.",
  "jal-el-bahr":
    "Jal El Bahr (Film)\n\nJal el Bahr is a personal essai that retraces the history of a 1960’s domain in the South of Lebanon and the family it belongs to. Between reminiscing and feeling of loss, the documentary shifts into a metaphorical universe by illustrating the story through living pictures, discretely unveiling the unspoken that might have led to its perdition.\n\nDirected by Racha Baroud\nDirector of Photography Nader Bahsoun\nSound Engineer Tatiana el Dahdah",
  "jess-and-alex":
    "Jessica & Alex (2021) Cinematic Wedding Film Some weddings don’t follow a script — no fixed plans, just real moments unfolding. The joy is unfiltered, the emotions genuine. When the energy flows freely, the camera becomes part of the celebration. Everyone’s having fun, including the videographer. That’s when the film becomes more than a record — it becomes a feeling.",
  msafreen:
    "MSAFREEN (music video)\nDirector, Cinematographer & Editor\nNADER BAHSOUN\nRapper\nMEHRAK\nMusic Production\nJUNDI MAJHUL",
  "new-page-2": "",
  noctiluca:
    "NOCTILŪCA Noctilūca explores the potential re-appropriation of a lost wild layer of being. In the pursuit of a disciplined and controlled society, sparks of dynamism and life force have been dulled. Awakening the tamed and penetrating the unknown, I reunite with my body, in the sway of a primordial tune. Choreography & Performance Yara Boustany Composer Giorgios Gargalas Artistic Collaborator Rach",
  "shabah-el-rih":
    "Shabah El Rih\n\nLe Grand Théâtre des Mille et Une Nuits is a historical landmark in the center of Beirut. Built in the late 1920s, it played host to international performances, films and was an icon of contemporary Middle Eastern culture. After the 1975 civil war, the building suffered structural damage and was eventually boardd up and forgotten. There was no attempt to revive the theater until the people’s revolution of 2019, which led to its barriers finally being pulled down.",
  "snakes-and-ladders":
    "SNAKES & LADDERS\n\nSnakes and Ladders is an imaginary excursion, examining darkness, metaphorically, sensorially and symbolically. Hopelessly powerless bodies move, scan a dying city, try to read the future in the dark. The film creates a duality between a human body and a concrete building - attempting to open pathways of perception by melting the fortifications of our constructed meanings – by observing matter and thought, in their raw form. In darkness, we construct, in light we deconstruct.\n\nCommissioned by MAQAMAT for BIPOD 2022, the film was screened at Sursok Palace as part of Cameras of October.\nSelected for screening at Cinedans FEST '22 and was featured in the International Short Film Competition.",
  "southern-birds-project":
    "SOUTHERN BIRDS\n\nMedium: Photography, video, altered archive\nFormat: Ongoing project\nYear: 2025\n\nThe South carries within it both confinement and possibility. It is a place shaped by survival, by a history of resistance that has defined not only the land but the people who inhabit it. To be from the South is to inherit both its burden and its clarity, to be shaped by a force that is at once protective and consuming. Resistance exists as more than an act—it is a condition, a structure through which identity is negotiated. It asks what it means to endure, and whether endurance alone is enough.\n\nHere, family and home are continuously threatened, reconstructed, and redefined. They are tied to land but also to memory, to what is passed down and what is left behind.\n\nFamily photo albums are left buried in the rubble of bombed homes, remnants of airstrikes and destruction. Warped and ruined, yet not erased. A search for more begins—digging, uncovering, collecting remnants of personal and collective histories left behind, unclaimed, abandoned as if they no longer mattered.\n\nFor me, the child appears neither consumed by nor separate from the adult world but moving through it—imitating, absorbing, or reflecting something beyond themselves. There is an unsettling proximity between play and possession, innocence and something more elusive, what is remembered and what is imagined. History becomes something not to be escaped but rather held.\n\nThe images take on a pulse, refusing disappearance. This archive is not a ruin but a process of becoming. Evidence of persistence, of history reshaping itself, of a future waiting to be provoked.",
  store: "",
  storeee: "",
  "subject-to-change":
    "SUBJECT TO CHANGE Ten minute video performance exhibited within the group show “I don’t want to talk, but..” at Zico House Beirut in August of 2021 Performed & Directed by THALIA BASSIM Cinematography NADER BAHSOUN",
  test9: "",
  "the-bleed-zine":
    "The Bleed Zine\nPhoto Serie\n\nNader deconstructs and examines the intricate layers of religious ritual and human emotion in The Bleed Zine, an ongoing photographic project centered on the Ashura ceremonies in Tyre, south of Lebanon. He questions traditional representations of this significant event, focusing on the collective expressions of devotion, grief, and solidarity.\n\nThrough black-and-white imagery and deliberate cropping techniques, he brings viewers intimately close to details that often go unnoticed— This approach offers a critical yet compassionate exploration of human expression and the fluid dynamics of the crowd.\n\nThe Bleed Zine unfolds as a study of movement and human expression, inviting viewers to discover the profound depths of a ritual that resonates far beyond its geographic origins.",
  "the-valley-of-sleep":
    "THE VALLEY OF SLEEP The Valley of Sleep exposes concealed territories of existence, revealing an indistinct chatter, an inner turmoil. In a convergence point between the intuitive and the rational, restless bodies simmer - infinite possibilities unfold. A turbulent enchanting dance dissects our imaginary. Performed by Alexandre Habre, Aymeric Lorthiois, Michael Castalan and Yara Boustany Dramaturg",
  "three-decades-and-a-climax":
    "Three Decades and a Climax\nA Photographic Reflection on Lebanon’s 2019 Uprising\n\nThis photographic project documents a pivotal moment in Lebanon’s recent history: the 2019 uprising, a spontaneous and nationwide protest movement that erupted after three decades of systemic corruption, political stagnation, and social decay. Sparked by a proposed tax on WhatsApp calls, the protests quickly evolved into a larger, unified cry against decades of mismanagement by a sectarian ruling elite that had long manipulated power-sharing to maintain their grip on the country.\n\nThrough intimate street photography, this project captures the collective pulse of a nation reclaiming its voice—young and old, from all sects and regions, occupying public squares and chanting for dignity, justice, and real change. The uprising was not merely political; it was deeply personal—a rupture in the public’s tolerance for humiliation, economic disenfranchisement, and eroded social trust.\n\nAs the protests unfolded, the underlying fragility of the Lebanese state became increasingly evident. What followed was one of the worst economic collapses in modern history: the national currency lost over 90% of its value, banks froze citizens’ savings, and poverty rates soared. Yet in the face of despair, the people’s presence in the streets marked a rare and powerful assertion of agency.\n\nThree Decades and a Climax is not only a visual archive—it is a meditation on resistance, hope, and the role of collective memory in shaping national identity. The images in this series serve as both testimony and mirror: documenting the fever of revolt while inviting the viewer to reflect on what remains after the chants fade and the streets empty.",
  "toujours-deux-editions":
    "Toujours Deux Éditions Every photograph I release exists in two editions—always. It’s a decision rooted in clarity, not strategy. One is made to be more accessible, the other to be held, collected, lived with over time. This isn’t about scarcity for its own sake. It’s about protecting the integrity of the image Small Collector Edition Created for circulation. Limited, accessible, and intentional. ",
  "unchild-print-edition":
    "Strange Fruit 120.00€-350.00€ The flood never stops #02 120.00€-350.00€ Petit Amour 120.00€-350.00€ Point and Kill 120.00€-350.00€ The flood never stops 120.00€-350.00€ Will you keep a secret? 120.00€-350.00€ Strange Fruit #02 120.00€-350.00€ Dreamers 120.00€-350.00€ Once, Twice, Wake up 120.00€-350.00€ Of heaven and mothers 120.00€-350.00€ Russian Roulette 120.00€-350.00€ Tyrianas 120.00€-350.00€",
  "unchild-print-edition-1":
    "I’ve always been drawn to how children move through the world—fully present, imaginative, and reflective of something far beyond themselves. Their ability to inhabit the moment blurs the lines between play and memory, innocence and experience. The unchild edition is a small collection of photographs I’ve taken of children over the years between my hometown Tyre and Beirut. 50% of all proceeds from",
  "unhearable-voices":
    "UNHEARABLE\nVOICES\n\nUnhearable Voices is an etude around the project What if those tears were not only mine?, a performance about unconscious heritage.\nThis movie was made in the frame of the Co-Labs residency in Amalgam Studio-Beirut in January 2022.\n\nDirected and performed by // Réalisation et performance :\nRacha Baroud\nAssistant director // Assistante à la mise en scène :\nRiwa Baroud\nCinematography // Directeur de la photographie :\nNader Bahsoun\nMusic composition // Compositeur\nCharbel Haber\nSound design // Design sonore :\nFadi Tabbal\nEditing // Montage\nNader Bahsoun",
  "w-adrian-pepe":
    "A Shroud Is a Cloth – Video Commission for Adrian Pepe Dubai, 2025 I was commissioned by artist Adrian Pepe to create a video piece for his solo exhibition A Shroud Is a Cloth , presented by NIKA Projects in Dubai. The exhibition explores the symbolism of the shroud as a transitional object—connecting land, body, ritual, and memory through the medium of wool. Responding to Adrian’s material-led pr",
  womena:
    "Womena : Everything Has Changed Filmed across Jeddah and Beirut, this docu-series explores the region’s evolving cultural landscapes through music, identity, and creative expression. Full videography and lighting were executed in collaboration with Womena’s creative team, with responsibilities spanning camera operation, on-location lighting setups, and visual direction. Filming took place in varie",
  "womena-beirut":
    "WOMENA EVERYTHING HAS CHANGED This series looks at the ways in which our lives have changed over the last decade, the realities we continue to carry with us and the new narratives we’ve adopted. “With a new wave of emigration from Lebanon in the last two years due to socioeconomic collapse, those who choose to return and remain, like myself, are becoming more of an anomaly,” says host Angela Bruss",
  "womena-sound-of-saudi-3":
    "Womena : Everything Has Changed Filmed across Jeddah and Beirut, this docu-series explores the region’s evolving cultural landscapes through music, identity, and creative expression. Full videography and lighting were executed in collaboration with Womena’s creative team, with responsibilities spanning camera operation, on-location lighting setups, and visual direction. Filming took place in varie",
  "work-1-1":
    "Content Creation ART EVOLUTION (GOETHE) VIDEO SERIES / CINEMATOGRAPHER & EDITOR WOMENA VIDEO SERIES / CINEMATOGRAPHER & EDITOR FRENCH EMBASSY PROMOTIONAL VIDEO / CINEMATOGRAPHER & EDITOR ZOUKAK VIDEO SERIES / CINEMATOGRAPHER & EDITOR DAFTAR BEIRUT VIDEO SERIES / CINEMATOGRAPHER & EDITOR ; 2023",
  "zoukak-theatre":
    "Zoukak Theatre Video Series Mentorship Program - 2022 This series of videos was developed in collaboration with Zoukak Theatre Company as part of their Theatre Mentorship Program and Production Support Grant. Each video reflects the creative process, performance, or thematic exploration of artists engaged in Zoukak’s ongoing commitment to experimental and socially engaged theatre. Through close co",
};

const trimToLastSentence = (copy: string) => {
  const trimmed = copy.trim();
  if (!trimmed) return "";
  if (/[.!?…]$/.test(trimmed)) return trimmed;
  const match = trimmed.match(/[\s\S]*[.!?]/);
  return match ? match[0].trim() : trimmed;
};

export const getPageCopy = (slug: string) => {
  const copy = pageCopy[slug];
  if (!copy) return "";
  if (copy.includes("\n")) return copy.trim();
  return trimToLastSentence(copy);
};
